env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = QT_QPA_PLATFORM,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

env = MOZ_ENABLE_WAYLAND,1
env = HYPRLAND_NO_SD_NOTIFY=0

env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0
env = __GL_VRR_ALLOWED,0
env = NVD_BACKEND,direct
env = WLR_NO_HARDWARE_CURSORS,1

